version: '3.8'  # Specify the version of Docker Compose

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user           
      - POSTGRES_PASSWORD=password    # Set your default PostgreSQL password
      - POSTGRES_DB=crypto          # Set your default PostgreSQL database
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Volume for persisting RabbitMQ data

  ticker:
    build: ./ticker
    container_name: ticker
    depends_on:
      - rabbitmq
    environment:
      - RABBIT=amqp://user:password@rabbitmq
      - QUEUE=ticks
      - CONCURRENCY=5
      - DURATION=5s
      - WEBSOCKET=wss://ws.coincap.io/prices?assets=bitcoin,ethereum,monero,litecoin

  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    depends_on:
      - rabbitmq
    environment:
      - RABBIT=amqp://user:password@rabbitmq
      - QUEUE=ticks

volumes:
  postgres_data:
  rabbitmq_data: