version: '3.8'  # Specify the version of Docker Compose

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Volume for persisting RabbitMQ data

  ticker:
    build: ./ticker
    container_name: ticker
    depends_on:
      - rabbitmq
    environment:
      - RABBIT=amqp://user:password@rabbitmq
      - QUEUE=ticks
      - CONCURRENCY=5
      - DURATION=5s
      - WEBSOCKET=wss://ws.coincap.io/prices?assets=bitcoin,ethereum,monero,litecoin
  
  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    depends_on:
      - rabbitmq
    environment:
      - RABBIT=amqp://user:password@rabbitmq
      - QUEUE=ticks

volumes:
  rabbitmq_data:  # Define the volume